# agent.py
# PURPOSE: LangGraph agent — the orchestration brain
# FLOW: plan_research → search_web → synthesize_findings → write_report

from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage
from typing import TypedDict, Annotated, List
import operator   # for Annotated[List, operator.add] — appends lists
import json       # parse/create JSON strings
import re         # regex — find URLs in text

# Import from our other files
from llm import llm_large, llm_fast
from tools import web_search, scrape_page
from memory import remember, recall
from report import format_report


# ── STEP 1: Define State ──────────────────────────────────────────────
# ResearchState is a TypedDict — a dictionary with typed keys.
# This is the "shared memory" that flows between all nodes.
# Every node reads from it and writes back to it.
class ResearchState(TypedDict):
    topic:          str          # research topic entered by user
    queries:        List[str]    # search queries generated by planner

    # Annotated[List[str], operator.add] means:
    # when multiple nodes write to this field, APPEND (don't overwrite)
    search_results: Annotated[List[str], operator.add]
    scraped_pages:  Annotated[List[str], operator.add]

    findings:       str          # JSON string of synthesized findings
    citations:      List[dict]   # list of {claim, source} dicts
    report:         str          # final formatted report
    status:         str          # current step for progress display


# ── STEP 2: Node 1 — plan_research ───────────────────────────────────
# INPUT:  state with just 'topic' filled
# OUTPUT: state with 'queries' filled (list of search queries)
# USES:   llm_fast (simple task — just format a list)
def plan_research(state: ResearchState) -> dict:
    print("📋 Planning search queries...")

    # Ask LLM to generate specific search queries for this topic
    prompt = f"""Generate 4 specific search queries to research this topic thoroughly.
Cover different angles: overview, recent news, statistics, expert opinions.

Topic: {state['topic']}

Return ONLY valid JSON — no explanation, no markdown:
{{"queries": ["query1", "query2", "query3", "query4"]}}"""

    resp = llm_fast.invoke([HumanMessage(content=prompt)])

    try:
        # Strip markdown code fences if LLM added them
        text = resp.content.strip()
        text = text.replace("```json", "").replace("```", "").strip()
        data    = json.loads(text)
        queries = data["queries"]
    except:
        # Fallback if LLM doesn't return valid JSON
        queries = [
            state["topic"],
            f"{state['topic']} 2025 latest",
            f"{state['topic']} analysis",
            f"{state['topic']} research findings",
        ]

    print(f"   Generated queries: {queries}")
    # Return dict — LangGraph merges this into state
    return {"queries": queries, "status": "searching"}


# ── STEP 3: Node 2 — search_web ──────────────────────────────────────
# INPUT:  state with 'queries'
# OUTPUT: state with 'search_results' and 'scraped_pages' added
# USES:   web_search tool + scrape_page tool + memory.remember()
def search_web(state: ResearchState) -> dict:
    print("🔍 Searching the web...")
    results = []
    scraped = []

    for query in state["queries"][:4]:       # max 4 queries

        # Search DuckDuckGo
        raw = web_search.invoke({"query": query, "max_results": 5})
        results.append(raw)

        # Store search results in vector memory
        remember(raw, {"topic": state["topic"], "type": "search"})

        # Extract URLs from results using regex
        # r'URL: (https?://\S+)' matches "URL: https://example.com"
        urls = re.findall(r'URL: (https?://\S+)', raw)[:2]

        for url in urls:
            print(f"   📄 Scraping: {url[:55]}...")
            page = scrape_page.invoke({"url": url})
            scraped.append(page)

            # Store scraped content in vector memory too
            remember(page, {"topic": state["topic"], "url": url})

    print(f"   Scraped {len(scraped)} pages, stored in memory")
    return {
        "search_results": results,
        "scraped_pages": scraped,
        "status": "synthesizing"
    }


# ── STEP 4: Node 3 — synthesize_findings ─────────────────────────────
# INPUT:  state with all scraped content in memory
# OUTPUT: state with 'findings' (JSON) and 'citations'
# USES:   memory.recall() to get relevant chunks + llm_large to reason
def synthesize_findings(state: ResearchState) -> dict:
    print("🧠 Synthesizing findings from memory...")

    # Retrieve the 8 most relevant chunks from memory
    relevant = recall(state["topic"], n=8)
    context  = "\n\n---\n\n".join(relevant)

    prompt = f"""You are a research analyst. Analyze the gathered content below and extract key findings.

Research Topic: {state['topic']}

Gathered Content:
{context[:5000]}

Return ONLY valid JSON (no markdown, no explanation):
{{
  "key_findings": ["finding1", "finding2", "finding3", "finding4"],
  "themes": ["theme1", "theme2", "theme3"],
  "evidence": [
    {{"claim": "specific claim from content", "source": "url or unknown"}}
  ],
  "gaps": ["what information is missing or unclear"]
}}"""

    resp = llm_large.invoke([HumanMessage(content=prompt)])

    try:
        text = resp.content.strip()
        text = text.replace("```json", "").replace("```", "").strip()
        data      = json.loads(text)
        citations = data.get("evidence", [])
    except:
        data      = {"key_findings": [resp.content[:500]]}
        citations = []

    print(f"   Found {len(data.get('key_findings',[]))} key findings")
    return {
        "findings":  json.dumps(data),
        "citations": citations,
        "status":    "writing"
    }


# ── STEP 5: Node 4 — write_report ────────────────────────────────────
# INPUT:  state with 'findings' JSON
# OUTPUT: state with 'report' (formatted markdown string)
# USES:   llm_large for writing + format_report() to save file
def write_report(state: ResearchState) -> dict:
    print("✍️  Writing final report...")

    # Parse findings JSON back to dict
    findings = json.loads(state["findings"])

    prompt = f"""You are a professional research writer. Write a comprehensive research report.

Topic: {state['topic']}

Key Findings: {findings.get('key_findings', [])}
Themes: {findings.get('themes', [])}
Evidence: {findings.get('evidence', [])}
Gaps: {findings.get('gaps', [])}

Write a well-structured markdown report with these sections:
## Executive Summary
## Background
## Key Findings
## Analysis & Themes
## Limitations & Gaps
## Conclusion

Be specific, use the evidence provided, write for a professional audience."""

    resp   = llm_large.invoke([HumanMessage(content=prompt)])

    # Save and format the report
    report = format_report(
        topic=state["topic"],
        content=resp.content,
        citations=state["citations"]
    )
    return {"report": report, "status": "done"}


# ── STEP 6: Build the LangGraph ───────────────────────────────────────
# This assembles all nodes into a directed graph and compiles it.
def build_agent():
    # Create graph with our state type
    g = StateGraph(ResearchState)

    # Add nodes (name → function)
    g.add_node("plan",       plan_research)
    g.add_node("search",     search_web)
    g.add_node("synthesize", synthesize_findings)
    g.add_node("write",      write_report)

    # Set entry point — which node runs first
    g.set_entry_point("plan")

    # Add edges — the flow between nodes
    g.add_edge("plan",       "search")    # plan → search
    g.add_edge("search",     "synthesize") # search → synthesize
    g.add_edge("synthesize", "write")      # synthesize → write
    g.add_edge("write",      END)           # write → done

    # MemorySaver = checkpointer that saves state in RAM
    # (use SqliteSaver for persistence across restarts)
    from langgraph.checkpoint.memory import MemorySaver
    return g.compile(checkpointer=MemorySaver())


# Build agent when this file is imported
agent = build_agent()